In [14]:
# Debemos importar numpy
# le designamos el nombre np
import sys
import numpy as np

In [4]:
# creamos un array basico 
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
#colocamos el array dentro de la variable a 
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
#el array puede contener nros int, float, negative
b=np.array([1,-5, 1.4,7])
b

array([ 1. , -5. ,  1.4,  7. ])

In [10]:
#extraemos de la variable a los valores del indice 0 y 1
a[0] ,a[1]

(1, 2)

In [11]:
#extraemos los valores del indice 2 y 3
b[2],b[3]

(1.4, 7.0)

In [12]:
#extrae todos los elementos
a[0:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#extrae del 1 al 3 sin incluir el valor del indice 3 
a[1:3]

array([2, 3])

In [14]:
#extrae los valores de 2 en 2
a[::2]

array([1, 3, 5, 7])

In [15]:
#extrae de 3 en 3 
a[::3]

array([1, 4, 7])

In [16]:
#nos muestra los tipos de datos int, float
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [18]:
#trasforma el valor int en float 
np.array([1,2,3,4],dtype=np.float)

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_4516/2214947681.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4],dtype=np.float)


array([1., 2., 3., 4.])

In [19]:
np.array([1,2,3,4],dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
c=np.array(['a','b','c'])
c

array(['a', 'b', 'c'], dtype='<U1')

In [22]:
#U1 es la representacion unicode
c.dtype

dtype('<U1')

In [25]:
#creamos matrices multidimensionales
a=np.array([[1,2,3],[4,5,6]])
a
#nos devuelve una matriz de 2x3 bidimensional


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#nos muestra el tipo de matrix
#2 filas y 3 columnas 
a.shape

(2, 3)

In [27]:
#nos dice la dimension de la matriz 
a.ndim

2

In [28]:
#muestra los valores dentro de la matriz 
a.size

6

In [31]:
#creamos una matriz tridimensional 
b=np.array([[[12,11,10],[9,8,7]]
            ,[[6,5,4],[3,2,1]]])
b

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [32]:
b.shape

(2, 2, 3)

In [33]:
b.ndim

3

In [34]:
b.size

12

In [35]:
#indexar y dividir matrices 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
#me dice la fila 1
a[1]

array([4, 5, 6])

In [38]:
#fila 2 primer elemento
a[1][0]

4

In [39]:
a[1,0]

4

In [40]:
#selecciono todo hasta la fila 2 
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#selecciona todas las filas y las 2 primeras columnas 
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
#selecciona hasta la 2 fila y ultima columna 
a[:2,2:]

array([[3],
       [6]])

In [45]:
#la fila 1 la mabiamos por un array de 10,10,10
a[1]=np.array([10,10,10])
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [46]:
a[2]=np.array([99,99,99])
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [47]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [48]:
#suma todos los valores
a.sum()

10

In [49]:
#promedia todo los valores 
a.mean()

2.5

In [50]:
#desviacion standar 
a.std()

1.118033988749895

In [51]:
#varianza 
a.var()

1.25

In [52]:
a.sum(axis=0)

10

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
#me suma los valores de las columnas 
a.sum(axis=0)

array([12, 15, 18])

In [57]:
#suma los valores de las filas 
a.sum(axis=1)

array([ 6, 15, 24])

In [59]:
#vectorizacion 
a=np.arange(4)
a

array([0, 1, 2, 3])

In [60]:
#le sumo 10 a cada elemento del array 
a +10

array([10, 11, 12, 13])

In [61]:
a*10  #multiplico por 10 cada elemento del array 

array([ 0, 10, 20, 30])

In [66]:
a +=100
a

array([500, 501, 502, 503])

In [67]:
l=[0,1,2,3]
[i *10 for i in l]




[0, 10, 20, 30]

In [68]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [69]:
b=np.array([2,3,4,5])
b

array([2, 3, 4, 5])

In [70]:
a+b

array([2, 4, 6, 8])

In [71]:
a*b

array([ 0,  3,  8, 15])

In [4]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [7]:
#necesitamos el 1 y el ultimo elemento 
a[[0,-1]]

array([0, 3])

In [9]:
a[[True, False, False, True]]


array([0, 3])

In [10]:
a>=2

array([False, False,  True,  True])

In [11]:
a[a>=2]

array([2, 3])

In [13]:
#contruye una matrix de 3x3 com valores aleatorios hasta 100
a=np.random.randint(100,size=(3,3))
a

array([[74, 47, 29],
       [14, 95, 12],
       [22, 58, 68]])

In [15]:
#motor regular en python 
#28 nro de bytes que almacena en python 
sys.getsizeof(1)

28

In [17]:
np.dtype(int).itemsize

4

In [18]:
np.dtype(float).itemsize

8

In [20]:
l=list(range(1000))


In [22]:
a=np.arange(1000)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18