In [41]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a.ndim
print(a)

[1 2 3]


In [8]:
b.ndim
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int32')

In [11]:
a.itemsize

4

In [12]:
b.itemsize

8

In [16]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
c.shape

(2, 7)

In [17]:
#cuando hacemos la busqueda por indices la primero son , 
#las filas rows y luego las columnas columns
#si queremos obtener el nro 13 
c[1,5]

13

In [18]:
#seleccionar la row completa 
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
#seleccionar una columna 
c[:,2]

array([ 3, 10])

In [20]:
#cambiar un valor de indice 
c[1,5]=20
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [26]:
np.random.rand(4,2)

array([[0.21616127, 0.692748  ],
       [0.11652424, 0.71391061],
       [0.68071506, 0.0142067 ],
       [0.41825098, 0.01028063]])

In [27]:
np.random.randint(7, size=(3,3))

array([[2, 4, 5],
       [0, 2, 3],
       [2, 4, 0]])

In [28]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [30]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=7
print(z)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 7. 0.]
 [0. 0. 0.]]


In [34]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [35]:
a +2

array([3, 4, 5])

In [36]:
a-2

array([-1,  0,  1])

In [37]:
a*3

array([3, 6, 9])

In [38]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [39]:
a+b

array([2, 4, 6])

In [48]:
filedata=np.genfromtxt('data.txt', delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19., 20., 21.]])

In [49]:
filedata <50

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [50]:
filedata >22

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [51]:
filedata[filedata <50]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21.])

In [53]:
((filedata <50) & (filedata >22))

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])